# This is a basic workflow to help you get started with Actions

name: variables
run-name: Â¡Estoy aprendiendo a usar variables!

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["aprendiendo-github-actions"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  not-main:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Esta NO es la rama main, es ${{ github.ref_name }}"
      - run: echo "El actor es ${{ github.actor }}"
      - run: echo "El evento es ${{ github.event_name }}"
      - run: echo "Desplegando en la rama $GITHUB_REF del repo de ${{ vars.NAME }}"
